version: '3.8'

networks:
  anlix_challenge_network:

volumes:
  database_data:

services:

  # Postgres
  database:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "anlix_db"
    ports:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - anlix_challenge_network

  # springboot
  back:
    image: docker.pkg.github.com/aurinosalvador/anlix-api/anlix-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/anlix_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      ports:
        - "8080:8080"
      networks:
        - anlix_challenge_network
      depends_on:
        - database

  # Flutter
  front:
    image: docker.pkg.github.com/aurinosalvador/anlix_front/anlix-front:latest
    environment:
      ports:
        - "80:80"
      networks:
        - anlix_challenge_network
      depends_on:
        - database
        - back

