name: anlix_front
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.3+4

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  # https://pub.dev/packages/charts_flutter
  charts_flutter: 0.12.0
  # https://pub.dev/packages/csv
  csv: 5.0.1

  cupertino_icons: 1.0.2

  # https://pub.dev/packages/file_picker
  file_picker: 4.3.3

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/http
  http: 0.13.4
  # https://pub.dev/packages/intl
  intl: 0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
